
CHANNEL = "GUILD"
CEPGP_lootChannel = "RAID"
COEF = 5
MOD_COEF = 1
MOD = 1
AUTOEP = {
	["High Priestess Jeklik"] = true,
	["Gothik the Harvester"] = true,
	["Buru the Gorger"] = true,
	["Wushoolay"] = true,
	["Lord Kri"] = true,
	["Emperor Vek'nilash"] = true,
	["Ossirian the Unscarred"] = true,
	["Golemagg the Incinerator"] = true,
	["Grand Widow Faerlina"] = true,
	["High Priestess Mar'li"] = true,
	["Majordomo Executus"] = true,
	["High Priest Venoxis"] = true,
	["Gehennas"] = true,
	["Taerar"] = true,
	["Ysondre"] = true,
	["Thane Korth'azz"] = true,
	["High Priest Thekal"] = true,
	["Noth the Plaguebringer"] = true,
	["Lethon"] = true,
	["Moam"] = true,
	["The Prophet Skeram"] = true,
	["Flamegor"] = true,
	["C'Thun"] = true,
	["General Rajaxx"] = true,
	["Princess Huhuran"] = true,
	["Thaddius"] = true,
	["Loatheb"] = true,
	["Lady Blaumeux"] = true,
	["Highlord Mograine"] = true,
	["Heigan the Unclean"] = true,
	["Azuregos"] = true,
	["Doom Lord Kazzak"] = true,
	["Teremus the Devourer"] = true,
	["Chromaggus"] = true,
	["Baron Geddon"] = true,
	["Firemaw"] = true,
	["Sulfuron Harbinger"] = true,
	["Gri'lek"] = true,
	["High Priestess Arlokk"] = true,
	["Emperor Vek'lor"] = true,
	["Gahz'ranka"] = true,
	["Gluth"] = true,
	["Sapphiron"] = true,
	["Razorgore the Untamed"] = true,
	["Onyxia"] = true,
	["Princess Yauj"] = true,
	["Vem"] = true,
	["Shazzrah"] = true,
	["Ouro"] = true,
	["Battleguard Sartura"] = true,
	["Maexxna"] = true,
	["Kel'Thuzad"] = true,
	["Nefarian"] = true,
	["Fankriss the Unyielding"] = true,
	["Lucifron"] = true,
	["Anub'Rekhan"] = true,
	["Hazza'rah"] = true,
	["Ragnaros"] = true,
	["Ayamiss the Hunter"] = true,
	["Broodlord Lashlayer"] = true,
	["Viscidus"] = true,
	["Hakkar"] = true,
	["Ebonroc"] = true,
	["Kurinnaxx"] = true,
	["Grobbulus"] = true,
	["Instructor Razuvious"] = true,
	["Emeriss"] = true,
	["Magmadar"] = true,
	["Sir Zeliek"] = true,
	["Vaelastrasz the Corrupt"] = true,
	["Patchwerk"] = true,
	["Bloodlord Mandokir"] = true,
	["Renataki"] = true,
	["Jin'do the Hexxer"] = true,
	["Garr"] = true,
}
EPVALS = {
	["High Priestess Jeklik"] = 2,
	["Gothik the Harvester"] = 12,
	["Buru the Gorger"] = 3,
	["Wushoolay"] = 2,
	["Lord Kri"] = 10,
	["Emperor Vek'nilash"] = 10,
	["Ossirian the Unscarred"] = 4,
	["Golemagg the Incinerator"] = "4",
	["Grand Widow Faerlina"] = 12,
	["High Priestess Mar'li"] = 2,
	["Majordomo Executus"] = "4",
	["High Priest Venoxis"] = 2,
	["Gehennas"] = "4",
	["Taerar"] = 7,
	["Ysondre"] = 7,
	["Thane Korth'azz"] = 15,
	["High Priest Thekal"] = 2,
	["Noth the Plaguebringer"] = 12,
	["Lethon"] = 7,
	["Moam"] = 3,
	["The Prophet Skeram"] = 10,
	["Flamegor"] = 7,
	["C'Thun"] = 12,
	["General Rajaxx"] = 3,
	["Princess Huhuran"] = 10,
	["Thaddius"] = 15,
	["Loatheb"] = 15,
	["Lady Blaumeux"] = 15,
	["Highlord Mograine"] = 15,
	["Heigan the Unclean"] = 12,
	["Azuregos"] = 7,
	["Doom Lord Kazzak"] = 7,
	["Teremus the Devourer"] = 7,
	["Chromaggus"] = 7,
	["Baron Geddon"] = "4",
	["Firemaw"] = 7,
	["Sulfuron Harbinger"] = "4",
	["Gri'lek"] = 2,
	["High Priestess Arlokk"] = 2,
	["Emperor Vek'lor"] = 10,
	["Gahz'ranka"] = 2,
	["Gluth"] = 12,
	["Sapphiron"] = 15,
	["Razorgore the Untamed"] = 7,
	["Onyxia"] = "4",
	["Princess Yauj"] = 10,
	["Vem"] = 10,
	["Shazzrah"] = "4",
	["Ouro"] = 10,
	["Battleguard Sartura"] = 10,
	["Maexxna"] = 15,
	["Kel'Thuzad"] = 15,
	["Nefarian"] = 10,
	["Fankriss the Unyielding"] = 10,
	["Lucifron"] = "2",
	["Anub'Rekhan"] = 12,
	["Hazza'rah"] = 2,
	["Ragnaros"] = "4",
	["Ayamiss the Hunter"] = 3,
	["Broodlord Lashlayer"] = 7,
	["Viscidus"] = 10,
	["Hakkar"] = 3,
	["Ebonroc"] = 7,
	["Kurinnaxx"] = 3,
	["Grobbulus"] = 12,
	["Instructor Razuvious"] = 12,
	["Emeriss"] = 7,
	["Magmadar"] = "4",
	["Sir Zeliek"] = 15,
	["Vaelastrasz the Corrupt"] = 7,
	["Patchwerk"] = 12,
	["Bloodlord Mandokir"] = 2,
	["Renataki"] = 2,
	["Jin'do the Hexxer"] = 2,
	["Garr"] = "4",
}
BASEGP = 10
STANDBYEP = false
STANDBYOFFLINE = false
STANDBYPERCENT = 100
STANDBYRANKS = {
	{
		"会长", -- [1]
		false, -- [2]
	}, -- [1]
	{
		"副会长", -- [1]
		false, -- [2]
	}, -- [2]
	{
		"官员", -- [1]
		false, -- [2]
	}, -- [3]
	{
		"二团老铁", -- [1]
		true, -- [2]
	}, -- [4]
	{
		"一团老铁", -- [1]
		false, -- [2]
	}, -- [5]
	{
		"会员", -- [1]
		false, -- [2]
	}, -- [6]
	{
		"小黑屋", -- [1]
		false, -- [2]
	}, -- [7]
	{
		"新兵", -- [1]
		false, -- [2]
	}, -- [8]
	{
		"", -- [1]
		false, -- [2]
	}, -- [9]
	{
		"", -- [1]
		false, -- [2]
	}, -- [10]
}
SLOTWEIGHTS = {
	["2HWEAPON"] = 4,
	["NECK"] = 2,
	["HEAD"] = 1,
	["WEAPON"] = 1.5,
	["WRIST"] = 1,
	["WEAPONMAINHAND"] = 4,
	["SHIELD"] = 4,
	["HOLDABLE"] = 4,
	["RANGED"] = 4,
	["SHOULDER"] = 1,
	["FEET"] = 1,
	["LEGS"] = 1,
	["EXCEPTION"] = 1,
	["WAIST"] = 1,
	["TRINKET"] = 4,
	["HAND"] = 1,
	["ROBE"] = 1,
	["CHEST"] = 1,
	["CLOAK"] = 1,
	["FINGER"] = 2,
	["WEAPONOFFHAND"] = 4,
	["RANGEDRIGHT"] = 4,
	["RELIC"] = 4,
	["THROWN"] = 4,
}
RECORDS = {
	["test"] = {
		["Kisayummi-Whitemane"] = "0,120",
		["Angelabeibei-Whitemane"] = "0,120",
		["Uco-Whitemane"] = "0,120",
		["Lawuyanzu-Whitemane"] = "0,120",
		["Musi-Whitemane"] = "0,120",
		["Pseudocold-Whitemane"] = "0,120",
		["Zaj-Whitemane"] = "0,120",
		["Demiguise-Whitemane"] = "0,120",
		["Valdesdly-Whitemane"] = "0,120",
		["Preserby-Whitemane"] = "0,120",
		["Alanjll-Whitemane"] = "0,120",
		["Darkswan-Whitemane"] = "0,120",
		["Luojiahao-Whitemane"] = "0,120",
		["Maxver-Whitemane"] = "0,120",
		["Xxsfans-Whitemane"] = "0,120",
		["Saitamazopm-Whitemane"] = "0,120",
		["Rotkisburing-Whitemane"] = "0,120",
		["Blkdoctor-Whitemane"] = "0,120",
		["Sonlyx-Whitemane"] = "0,120",
		["Frogtiny-Whitemane"] = "0,120",
		["Misshan-Whitemane"] = "0,120",
		["Biebibi-Whitemane"] = "0,120",
		["Noeita-Whitemane"] = "0,120",
		["Coldaurora-Whitemane"] = "0,120",
		["Mochis-Whitemane"] = "0,120",
		["Brosewagon-Whitemane"] = "0,120",
		["Whiteintee-Whitemane"] = "0,120",
		["Aarcher-Whitemane"] = "0,120",
		["Ghostbehind-Whitemane"] = "0,120",
		["Gnikore-Whitemane"] = "0,120",
		["Paytwobag-Whitemane"] = "0,120",
		["Tinaer-Whitemane"] = "0,120",
		["Deeplady-Whitemane"] = "0,120",
		["Xyzrouty-Whitemane"] = "0,120",
		["Cutemonday-Whitemane"] = "0,120",
		["Jojoyone-Whitemane"] = "0,120",
		["Magikarps-Whitemane"] = "0,120",
		["Lunargirl-Whitemane"] = "0,120",
		["Cokekiller-Whitemane"] = "0,120",
		["Bingfa-Whitemane"] = "0,120",
		["Benbensao-Whitemane"] = "0,120",
		["Dsmonkey-Whitemane"] = "0,120",
		["Knitz-Whitemane"] = "0,120",
		["Chowbusvan-Whitemane"] = "0,120",
		["Shing-Whitemane"] = "0,120",
		["Ironskin-Whitemane"] = "0,120",
		["Lemonsushi-Whitemane"] = "0,120",
		["Qqggff-Whitemane"] = "0,120",
		["Franku-Whitemane"] = "0,120",
		["Robinqaq-Whitemane"] = "0,120",
		["Lifeisgame-Whitemane"] = "0,120",
		["Crescenia-Whitemane"] = "0,120",
		["Momokano-Whitemane"] = "0,120",
		["Xarin-Whitemane"] = "0,120",
		["Lycoris-Whitemane"] = "0,120",
		["Mangfu-Whitemane"] = "0,120",
		["Rodnik-Whitemane"] = "0,120",
		["Blackwhiske-Whitemane"] = "0,120",
		["Miclong-Whitemane"] = "0,120",
		["Maokai-Whitemane"] = "0,120",
		["Ironpillar-Whitemane"] = "0,120",
		["Songisdone-Whitemane"] = "0,120",
		["Milkmummy-Whitemane"] = "0,120",
		["Answord-Whitemane"] = "0,120",
		["Rainbowbb-Whitemane"] = "0,120",
		["Angryknight-Whitemane"] = "0,120",
		["Angellun-Whitemane"] = "0,120",
		["Hitsoysauce-Whitemane"] = "10,120",
		["Phoniex-Whitemane"] = "0,120",
		["Zouhaobyebye-Whitemane"] = "0,120",
		["Huawei-Whitemane"] = "0,120",
		["Mintdurex-Whitemane"] = "0,120",
		["Ohayo-Whitemane"] = "0,120",
		["Zhangduwei-Whitemane"] = "0,120",
		["Healingwound-Whitemane"] = "0,120",
		["Parimuna-Whitemane"] = "0,120",
		["Jiahao-Whitemane"] = "0,120",
		["Angrysoul-Whitemane"] = "0,120",
		["Jbbald-Whitemane"] = "0,120",
		["Soulofarthas-Whitemane"] = "0,120",
		["Kenhaha-Whitemane"] = "0,120",
		["Showlenm-Whitemane"] = "0,120",
		["Smileapply-Whitemane"] = "0,120",
		["Tuyouqiang-Whitemane"] = "0,120",
		["Hakulamatata-Whitemane"] = "0,120",
		["Jieli-Whitemane"] = "0,120",
		["Melonpudding-Whitemane"] = "0,120",
		["Angdi-Whitemane"] = "0,120",
		["Xinkuzi-Whitemane"] = "0,120",
		["Daboba-Whitemane"] = "0,120",
		["Cnboy-Whitemane"] = "0,120",
		["Rafal-Whitemane"] = "0,120",
		["Titanhecate-Whitemane"] = "0,120",
		["Quge-Whitemane"] = "0,120",
		["Dmipk-Whitemane"] = "0,120",
		["Titoto-Whitemane"] = "0,120",
		["Bigbaldguy-Whitemane"] = "0,120",
		["Jkuo-Whitemane"] = "0,120",
		["Titune-Whitemane"] = "0,120",
		["Fiancée-Whitemane"] = "0,120",
		["Fallenleaves-Whitemane"] = "0,120",
		["Moommo-Whitemane"] = "0,120",
		["Chengming-Whitemane"] = "0,120",
		["Bigfatjoe-Whitemane"] = "0,120",
		["Shavronne-Whitemane"] = "0,120",
		["Zombiephobia-Whitemane"] = "0,120",
		["Destyjustc-Whitemane"] = "0,120",
		["Portion-Whitemane"] = "0,120",
		["Bigheiniu-Whitemane"] = "0,120",
		["Eroson-Whitemane"] = "0,120",
		["Dameng-Whitemane"] = "0,120",
		["Mortalstrik-Whitemane"] = "0,120",
		["Minikuku-Whitemane"] = "0,120",
		["Tzk-Whitemane"] = "0,120",
		["Googleming-Whitemane"] = "0,120",
		["Eachlessj-Whitemane"] = "0,120",
		["Teanswer-Whitemane"] = "0,120",
		["Roughncek-Whitemane"] = "0,120",
		["Crocodil-Whitemane"] = "0,120",
		["Udeni-Whitemane"] = "0,120",
		["Udairy-Whitemane"] = "0,120",
		["Wobaba-Whitemane"] = "0,120",
		["Geegeeboom-Whitemane"] = "0,120",
		["Kotoli-Whitemane"] = "0,120",
		["Bluehole-Whitemane"] = "0,120",
		["Abeaclan-Whitemane"] = "0,120",
		["Nimei-Whitemane"] = "0,120",
		["Tombradyy-Whitemane"] = "0,120",
		["Nikfury-Whitemane"] = "0,120",
		["Fafafazer-Whitemane"] = "0,120",
		["Mohan-Whitemane"] = "0,120",
		["Zeiniub-Whitemane"] = "0,120",
		["Gokusoul-Whitemane"] = "10,120",
		["Fishsheep-Whitemane"] = "0,120",
		["Guiguzi-Whitemane"] = "0,120",
		["Chengxuyuan-Whitemane"] = "0,120",
		["Plzletmemid-Whitemane"] = "0,120",
		["Cxkgogogo-Whitemane"] = "0,120",
		["Susubucirou-Whitemane"] = "0,120",
		["Immt-Whitemane"] = "0,120",
		["Electrino-Whitemane"] = "0,120",
		["Darktiger-Whitemane"] = "0,120",
		["Drlonng-Whitemane"] = "0,120",
		["Chubbie-Whitemane"] = "0,120",
		["Lostthunder-Whitemane"] = "0,120",
		["Panbie-Whitemane"] = "0,120",
		["Jandiya-Whitemane"] = "0,120",
		["Faz-Whitemane"] = "0,120",
		["Vinitus-Whitemane"] = "0,120",
		["Junmoxiao-Whitemane"] = "0,120",
		["Azogar-Whitemane"] = "0,120",
		["Deathcheater-Whitemane"] = "0,120",
		["Driftanselml-Whitemane"] = "0,120",
		["Playforuber-Whitemane"] = "0,120",
		["Lalafei-Whitemane"] = "0,120",
		["Chyxs-Whitemane"] = "0,120",
		["Hollowmage-Whitemane"] = "0,120",
		["Conquering-Whitemane"] = "0,120",
		["Holymacarone-Whitemane"] = "0,120",
		["Benshaman-Whitemane"] = "0,120",
		["Snowyice-Whitemane"] = "0,120",
		["Chrisah-Whitemane"] = "0,120",
		["Toxictotem-Whitemane"] = "0,120",
		["Glx-Whitemane"] = "0,120",
		["Hissbood-Whitemane"] = "0,120",
		["Casualwower-Whitemane"] = "0,120",
		["Omarlittlee-Whitemane"] = "0,120",
		["Febhoney-Whitemane"] = "0,120",
		["Laststorm-Whitemane"] = "0,120",
		["Naomicampbel-Whitemane"] = "0,120",
		["Demonshadow-Whitemane"] = "0,120",
		["Serialize-Whitemane"] = "0,120",
		["Darkages-Whitemane"] = "0,120",
		["Gigihadid-Whitemane"] = "0,120",
		["Tg-Whitemane"] = "0,120",
		["Hebiruci-Whitemane"] = "0,120",
		["Pluvette-Whitemane"] = "0,120",
		["Firefish-Whitemane"] = "0,120",
		["Socialmanlol-Whitemane"] = "0,120",
		["Murichael-Whitemane"] = "0,120",
		["Chuangshuoge-Whitemane"] = "0,120",
		["Twokickfeet-Whitemane"] = "0,120",
		["Bigoranges-Whitemane"] = "0,120",
		["Evilflower-Whitemane"] = "0,120",
		["Geili-Whitemane"] = "0,120",
		["Fortmdhorde-Whitemane"] = "0,120",
		["Nalus-Whitemane"] = "0,120",
		["Akiraorange-Whitemane"] = "0,120",
		["Ragingfury-Whitemane"] = "0,120",
		["Anmu-Whitemane"] = "0,120",
		["Ogremagii-Whitemane"] = "0,120",
		["Jackiejun-Whitemane"] = "0,120",
		["Thecupcake-Whitemane"] = "0,120",
		["Sickdog-Whitemane"] = "0,120",
		["Gameislife-Whitemane"] = "0,120",
		["Kumapaw-Whitemane"] = "0,120",
		["Deemo-Whitemane"] = "0,120",
		["Oldsha-Whitemane"] = "0,120",
		["Aros-Whitemane"] = "0,120",
		["Pluvian-Whitemane"] = "0,120",
		["Dragoncrepe-Whitemane"] = "0,120",
		["Mentholatun-Whitemane"] = "0,120",
		["Jojoo-Whitemane"] = "0,120",
		["Sanjidaoo-Whitemane"] = "0,120",
		["Imrice-Whitemane"] = "0,120",
		["Ellynnaqt-Whitemane"] = "0,120",
		["Huim-Whitemane"] = "0,120",
		["Amau-Whitemane"] = "0,120",
		["Mobai-Whitemane"] = "0,120",
		["Xcaliblog-Whitemane"] = "0,120",
		["Lastsummer-Whitemane"] = "0,120",
		["Checkid-Whitemane"] = "0,120",
		["Xiaolan-Whitemane"] = "0,120",
		["Granitee-Whitemane"] = "0,120",
		["Devilfordrin-Whitemane"] = "0,120",
		["Nianqing-Whitemane"] = "0,120",
		["Jojoml-Whitemane"] = "0,120",
		["Justaa-Whitemane"] = "0,120",
		["Baldstrong-Whitemane"] = "0,120",
		["Luvletter-Whitemane"] = "0,120",
		["Excaliblog-Whitemane"] = "0,120",
		["Muscleboi-Whitemane"] = "0,120",
		["Opic-Whitemane"] = "0,120",
		["Solaporschel-Whitemane"] = "0,120",
		["Jasonmagic-Whitemane"] = "0,120",
		["Pingo-Whitemane"] = "0,120",
		["Aizenn-Whitemane"] = "0,120",
		["Peonybunny-Whitemane"] = "0,120",
		["Apic-Whitemane"] = "0,120",
		["Rycie-Whitemane"] = "0,120",
		["Wagyubeef-Whitemane"] = "0,120",
		["Baiduu-Whitemane"] = "0,120",
		["Pigecha-Whitemane"] = "0,120",
		["Cossintan-Whitemane"] = "0,120",
		["Coquettish-Whitemane"] = "0,120",
		["Jjonak-Whitemane"] = "0,120",
		["Annagold-Whitemane"] = "0,120",
		["Hollicrab-Whitemane"] = "0,120",
		["Misyu-Whitemane"] = "0,120",
		["Larianna-Whitemane"] = "0,120",
		["Meitgao-Whitemane"] = "0,120",
		["Nidie-Whitemane"] = "0,120",
		["Pandaattack-Whitemane"] = "0,120",
		["Seniorita-Whitemane"] = "0,120",
		["Grumpybride-Whitemane"] = "0,120",
		["Jamest-Whitemane"] = "0,120",
		["Xiaoguangtou-Whitemane"] = "0,120",
		["Vollybear-Whitemane"] = "0,120",
		["Kamiorz-Whitemane"] = "0,120",
		["Rollingpunk-Whitemane"] = "0,120",
		["Purrple-Whitemane"] = "0,120",
		["Fashione-Whitemane"] = "0,120",
		["Jixiyuanzm-Whitemane"] = "0,120",
		["Kerryd-Whitemane"] = "0,120",
		["Railgun-Whitemane"] = "0,120",
		["Vforce-Whitemane"] = "0,120",
		["Cocococo-Whitemane"] = "0,120",
		["Oldguner-Whitemane"] = "0,120",
		["Iammt-Whitemane"] = "0,120",
		["Meleehuntre-Whitemane"] = "0,120",
		["Maokaiw-Whitemane"] = "0,120",
		["Mooncross-Whitemane"] = "0,120",
		["Yetee-Whitemane"] = "0,120",
		["Ohlalawu-Whitemane"] = "0,120",
		["Blacknwhite-Whitemane"] = "0,120",
		["Doubleice-Whitemane"] = "0,120",
		["Dreadbeef-Whitemane"] = "0,120",
		["Slaymoon-Whitemane"] = "0,120",
		["Madfurion-Whitemane"] = "0,120",
		["Ïf-Whitemane"] = "0,120",
		["Bibibaba-Whitemane"] = "0,120",
		["Canyoulayegg-Whitemane"] = "0,120",
		["Ruarotk-Whitemane"] = "0,120",
		["Niyeye-Whitemane"] = "0,120",
		["Yeshilani-Whitemane"] = "0,120",
		["Abysswalk-Whitemane"] = "0,120",
		["Cyotto-Whitemane"] = "0,120",
		["Krol-Whitemane"] = "0,120",
		["Aimuti-Whitemane"] = "0,120",
		["Bigwavesis-Whitemane"] = "0,120",
		["Akfaceshot-Whitemane"] = "0,120",
		["Lezio-Whitemane"] = "0,120",
		["Goodhunter-Whitemane"] = "0,120",
		["Babynight-Whitemane"] = "0,120",
		["Oothree-Whitemane"] = "0,120",
		["Lass-Whitemane"] = "0,120",
		["Dzz-Whitemane"] = "0,120",
		["Supplements-Whitemane"] = "0,120",
		["Sekosulordo-Whitemane"] = "0,120",
		["Screwdoor-Whitemane"] = "0,120",
		["Huicc-Whitemane"] = "0,120",
		["Aartlay-Whitemane"] = "0,120",
		["Lfyah-Whitemane"] = "0,120",
		["Cheran-Whitemane"] = "0,120",
		["Bomshakalaka-Whitemane"] = "0,120",
		["Novavon-Whitemane"] = "0,120",
		["Kuntukuta-Whitemane"] = "0,120",
		["Tarli-Whitemane"] = "0,120",
		["Liji-Whitemane"] = "0,120",
		["Alphas-Whitemane"] = "0,120",
		["Botakchin-Whitemane"] = "0,120",
		["Ivoray-Whitemane"] = "0,120",
		["Kfdandan-Whitemane"] = "0,120",
		["Mondayo-Whitemane"] = "0,120",
		["Karamay-Whitemane"] = "0,120",
		["Doomhammerx-Whitemane"] = "0,120",
		["Deadmushroom-Whitemane"] = "0,120",
		["Lilwhite-Whitemane"] = "0,120",
		["Yoyottv-Whitemane"] = "0,120",
		["Zuljiin-Whitemane"] = "0,120",
		["Nextmrning-Whitemane"] = "0,120",
		["Lightoff-Whitemane"] = "0,120",
		["Xiayuhe-Whitemane"] = "0,120",
		["Spartanjl-Whitemane"] = "0,120",
		["Effigon-Whitemane"] = "0,120",
		["Workingdad-Whitemane"] = "0,120",
		["Spiritleader-Whitemane"] = "0,120",
		["Shaunsheep-Whitemane"] = "0,120",
		["Pidan-Whitemane"] = "0,120",
		["Pythoneric-Whitemane"] = "0,120",
		["Hairwetdontc-Whitemane"] = "0,120",
		["Forsalock-Whitemane"] = "0,120",
		["Praisegaben-Whitemane"] = "0,120",
		["Lightup-Whitemane"] = "0,120",
		["Huofa-Whitemane"] = "0,120",
		["Caramelslife-Whitemane"] = "0,120",
		["Purplyfish-Whitemane"] = "0,120",
		["Mokiya-Whitemane"] = "0,120",
		["Kikoxx-Whitemane"] = "0,120",
		["Miriam-Whitemane"] = "0,120",
		["Pwu-Whitemane"] = "0,120",
		["Parousia-Whitemane"] = "0,120",
		["Uglyning-Whitemane"] = "0,120",
		["Xiaoyezi-Whitemane"] = "0,120",
		["Anying-Whitemane"] = "0,120",
		["Shinobuchan-Whitemane"] = "0,120",
		["Vanitoso-Whitemane"] = "0,120",
		["Starfear-Whitemane"] = "0,120",
		["Peachpeach-Whitemane"] = "0,120",
		["Ultrasoft-Whitemane"] = "0,120",
		["Kombie-Whitemane"] = "0,120",
		["Goskymonkey-Whitemane"] = "0,120",
		["Elmoretaro-Whitemane"] = "0,120",
		["Applesidra-Whitemane"] = "0,120",
		["Zouhaobyby-Whitemane"] = "0,120",
		["Zimoon-Whitemane"] = "0,120",
		["Mythrain-Whitemane"] = "0,120",
		["Avaloncy-Whitemane"] = "0,120",
		["Kumaclaw-Whitemane"] = "0,120",
		["Zafkiel-Whitemane"] = "0,120",
		["Doughgeh-Whitemane"] = "0,120",
		["Yuukimura-Whitemane"] = "0,120",
		["Yourolduncle-Whitemane"] = "0,120",
		["Shadowmoo-Whitemane"] = "0,120",
		["Plouton-Whitemane"] = "0,120",
		["Notsimple-Whitemane"] = "0,120",
		["Applewu-Whitemane"] = "0,120",
		["Gakki-Whitemane"] = "0,120",
		["Duckula-Whitemane"] = "0,120",
		["Usith-Whitemane"] = "0,120",
		["Tomorroww-Whitemane"] = "0,120",
		["Mewy-Whitemane"] = "0,120",
		["Erickahume-Whitemane"] = "0,120",
		["Xiaohuihui-Whitemane"] = "0,120",
		["Arlado-Whitemane"] = "0,120",
		["Sooha-Whitemane"] = "0,120",
		["Zhaowei-Whitemane"] = "0,120",
		["Bigchillx-Whitemane"] = "0,120",
		["Wuge-Whitemane"] = "0,120",
		["Xhh-Whitemane"] = "0,120",
		["Hoipaan-Whitemane"] = "0,120",
		["Alwaysdieme-Whitemane"] = "0,120",
		["Nuw-Whitemane"] = "0,120",
		["Liontyy-Whitemane"] = "0,120",
		["Grankain-Whitemane"] = "0,120",
		["Nimas-Whitemane"] = "0,120",
		["Asani-Whitemane"] = "0,120",
		["Rollhundred-Whitemane"] = "0,120",
		["Zhangmazi-Whitemane"] = "0,120",
		["Kubukio-Whitemane"] = "0,120",
		["Ninedraco-Whitemane"] = "0,120",
		["Wannister-Whitemane"] = "0,120",
		["Msith-Whitemane"] = "0,120",
		["Diabols-Whitemane"] = "0,120",
		["Biublubiu-Whitemane"] = "0,120",
		["Qiuqiu-Whitemane"] = "0,120",
		["Griffing-Whitemane"] = "0,120",
		["Madaoo-Whitemane"] = "0,120",
		["Bonushonor-Whitemane"] = "0,120",
		["Xiaobaifa-Whitemane"] = "0,120",
		["Bloodblood-Whitemane"] = "0,120",
		["Nightchef-Whitemane"] = "0,120",
		["Wayward-Whitemane"] = "0,120",
		["Mooguy-Whitemane"] = "0,120",
		["Acris-Whitemane"] = "0,120",
		["Melodyse-Whitemane"] = "0,120",
		["Frosttflame-Whitemane"] = "0,120",
		["Hypnosgl-Whitemane"] = "0,120",
		["Lovecraftt-Whitemane"] = "0,120",
		["Valdess-Whitemane"] = "0,120",
		["Luunna-Whitemane"] = "0,120",
		["Bengbengcha-Whitemane"] = "0,120",
		["Xiongtu-Whitemane"] = "0,120",
		["Knittz-Whitemane"] = "0,120",
		["Valdeslr-Whitemane"] = "0,120",
		["Valdesfs-Whitemane"] = "0,120",
		["Hahakeke-Whitemane"] = "0,120",
		["Cutemilka-Whitemane"] = "0,120",
		["Grouchygroom-Whitemane"] = "0,120",
		["Qilou-Whitemane"] = "0,120",
		["Miyamola-Whitemane"] = "0,120",
		["Mondaysha-Whitemane"] = "0,120",
		["Jasonm-Whitemane"] = "0,120",
		["Jucyboi-Whitemane"] = "0,120",
		["Neverlove-Whitemane"] = "0,120",
		["Afiona-Whitemane"] = "0,120",
		["Hugerabbitt-Whitemane"] = "0,120",
		["Undrej-Whitemane"] = "0,120",
		["Ivòry-Whitemane"] = "0,120",
		["Unclesam-Whitemane"] = "0,120",
		["Huang-Whitemane"] = "0,120",
		["Pembaba-Whitemane"] = "0,120",
		["Goblinmerch-Whitemane"] = "0,120",
		["Naiba-Whitemane"] = "0,120",
		["Lalidoli-Whitemane"] = "0,120",
		["Firekraker-Whitemane"] = "0,120",
		["Tebielv-Whitemane"] = "0,120",
		["Ulidian-Whitemane"] = "0,120",
		["Chengxuniu-Whitemane"] = "0,120",
		["Yatsuka-Whitemane"] = "0,120",
		["Shengwo-Whitemane"] = "0,120",
		["Sleepywayge-Whitemane"] = "0,120",
		["Sevetar-Whitemane"] = "0,120",
		["Gwokgwok-Whitemane"] = "0,120",
		["Cmsb-Whitemane"] = "0,120",
		["Wocao-Whitemane"] = "0,120",
		["Handwash-Whitemane"] = "0,120",
		["Greatflood-Whitemane"] = "0,120",
		["Nyaic-Whitemane"] = "0,120",
		["Foye-Whitemane"] = "0,120",
		["Tebiemeow-Whitemane"] = "0,120",
		["Xereup-Whitemane"] = "0,120",
		["Jumolie-Whitemane"] = "0,120",
		["Todeath-Whitemane"] = "0,120",
		["Greath-Whitemane"] = "0,120",
		["Blkbird-Whitemane"] = "0,120",
		["Silenx-Whitemane"] = "0,120",
		["Polymorphism-Whitemane"] = "0,120",
		["Shadowfiends-Whitemane"] = "0,120",
		["Feelnicd-Whitemane"] = "0,120",
		["Hkischnfver-Whitemane"] = "0,120",
		["Elyrath-Whitemane"] = "0,120",
		["Swagstab-Whitemane"] = "0,120",
		["Akumax-Whitemane"] = "0,120",
		["Iceiceices-Whitemane"] = "0,120",
		["Tinypeanut-Whitemane"] = "0,120",
		["Freecss-Whitemane"] = "0,120",
		["Huairen-Whitemane"] = "0,120",
		["Aslayer-Whitemane"] = "0,120",
		["Xiaoshenxian-Whitemane"] = "0,120",
		["Windseek-Whitemane"] = "0,120",
		["Swaggystab-Whitemane"] = "0,120",
		["Drunk-Whitemane"] = "0,120",
		["Shuaige-Whitemane"] = "0,120",
		["Superpao-Whitemane"] = "0,120",
		["Superbreadm-Whitemane"] = "0,120",
		["Tch-Whitemane"] = "0,120",
		["Umurr-Whitemane"] = "0,120",
		["Jezpali-Whitemane"] = "0,120",
		["Ssiren-Whitemane"] = "0,120",
		["Spz-Whitemane"] = "0,120",
		["Enricox-Whitemane"] = "0,120",
		["Raveen-Whitemane"] = "0,120",
		["Babiefat-Whitemane"] = "0,120",
		["Rickyboy-Whitemane"] = "0,120",
		["Spadesa-Whitemane"] = "0,120",
		["Snowplus-Whitemane"] = "0,120",
		["Mmatata-Whitemane"] = "0,120",
		["Sinledog-Whitemane"] = "0,120",
		["Sohard-Whitemane"] = "0,120",
		["Darkraging-Whitemane"] = "0,120",
		["Snowhite-Whitemane"] = "0,120",
		["Smallwhite-Whitemane"] = "0,120",
		["Iòiól-Whitemane"] = "0,120",
		["Tencent-Whitemane"] = "0,120",
		["Kksuper-Whitemane"] = "0,120",
		["Reagana-Whitemane"] = "0,120",
		["Docham-Whitemane"] = "0,120",
		["Tongbutong-Whitemane"] = "0,120",
		["Tebiegao-Whitemane"] = "0,120",
		["Gunzerker-Whitemane"] = "0,120",
		["Sleepysheep-Whitemane"] = "0,120",
		["Manbearbig-Whitemane"] = "0,120",
		["Dedep-Whitemane"] = "0,120",
		["Ascarchii-Whitemane"] = "0,120",
		["Shanqi-Whitemane"] = "0,120",
		["Todaysohappy-Whitemane"] = "0,120",
		["Bigma-Whitemane"] = "0,120",
		["Lalalalisa-Whitemane"] = "0,120",
		["Shadowlead-Whitemane"] = "0,120",
		["Bloodsea-Whitemane"] = "0,120",
		["Shadower-Whitemane"] = "0,120",
		["Bizdcheating-Whitemane"] = "0,120",
		["Changzhou-Whitemane"] = "0,120",
		["Diabol-Whitemane"] = "0,120",
		["Seacatx-Whitemane"] = "0,120",
		["Schoko-Whitemane"] = "0,120",
		["Savannaah-Whitemane"] = "0,120",
		["Amefu-Whitemane"] = "0,120",
		["Rainbowbaby-Whitemane"] = "0,120",
		["Ragie-Whitemane"] = "0,120",
		["Whosnxt-Whitemane"] = "0,120",
		["Benjx-Whitemane"] = "0,120",
		["Jaf-Whitemane"] = "0,120",
		["Papafrank-Whitemane"] = "0,120",
		["Dalabengba-Whitemane"] = "0,120",
		["Unidentify-Whitemane"] = "0,120",
		["Bigrogue-Whitemane"] = "0,120",
		["Duckson-Whitemane"] = "0,120",
		["Dragons-Whitemane"] = "0,120",
		["Leepeak-Whitemane"] = "0,120",
		["Myinvtwo-Whitemane"] = "0,120",
		["Nakedchatol-Whitemane"] = "0,120",
		["Firefarmer-Whitemane"] = "0,120",
		["Noturnonred-Whitemane"] = "0,120",
		["Fantariayy-Whitemane"] = "0,120",
		["Balabala-Whitemane"] = "0,120",
		["Erjiu-Whitemane"] = "0,120",
		["Colawithice-Whitemane"] = "0,120",
		["Whosfrst-Whitemane"] = "0,120",
		["Yiqilnoue-Whitemane"] = "0,120",
		["Warlockdaddy-Whitemane"] = "0,120",
		["Wthie-Whitemane"] = "0,120",
		["Hongshixian-Whitemane"] = "0,120",
		["Lowning-Whitemane"] = "0,120",
		["Gugu-Whitemane"] = "0,120",
		["Swagshifty-Whitemane"] = "0,120",
		["Elsb-Whitemane"] = "0,120",
		["Finallz-Whitemane"] = "0,120",
		["Laysbbq-Whitemane"] = "0,120",
		["Xiaoshuaige-Whitemane"] = "0,120",
		["Xiaxia-Whitemane"] = "0,120",
		["Kagmin-Whitemane"] = "0,120",
		["Biubia-Whitemane"] = "0,120",
		["Xiaozhou-Whitemane"] = "0,120",
		["Dajiji-Whitemane"] = "0,120",
	},
}
OVERRIDE_INDEX = {
}
TRAFFIC = {
	{
		"Guild", -- [1]
		"Gokusoul", -- [2]
		"Cleared EPGP standings (prepare for raid 2)", -- [3]
		"", -- [4]
		"", -- [5]
		"", -- [6]
		"", -- [7]
		"", -- [8]
		1574271818, -- [9]
	}, -- [1]
	{
		"Raid", -- [1]
		"Gokusoul", -- [2]
		"Add Raid EP +10 (test)", -- [3]
		"", -- [4]
		"", -- [5]
		"", -- [6]
		"", -- [7]
		"", -- [8]
		1574272287, -- [9]
	}, -- [2]
	{
		"Guild", -- [1]
		"Gokusoul", -- [2]
		"Cleared EPGP standings (init for raid team 2)", -- [3]
		"", -- [4]
		"", -- [5]
		"", -- [6]
		"", -- [7]
		"", -- [8]
		1574380421, -- [9]
	}, -- [3]
	{
		"Raid", -- [1]
		"Peachpeach", -- [2]
		"Add Raid EP +1 (11/21_jihe)", -- [3]
		"", -- [4]
		"", -- [5]
		"", -- [6]
		"", -- [7]
		[9] = 1574392160,
	}, -- [4]
	{
		"Raid", -- [1]
		"Peachpeach", -- [2]
		"Add Raid EP +5 - Lucifron", -- [3]
		"", -- [4]
		"", -- [5]
		"", -- [6]
		"", -- [7]
		[9] = 1574402767,
	}, -- [5]
	{
		"Raid", -- [1]
		"Peachpeach", -- [2]
		"Add Raid EP +2 (push 1)", -- [3]
		"", -- [4]
		"", -- [5]
		"", -- [6]
		"", -- [7]
		[9] = 1574402865,
	}, -- [6]
	{
		"Nidie", -- [1]
		"Peachpeach", -- [2]
		"Add GP 5 (t1 hand)", -- [3]
		"8", -- [4]
		"8", -- [5]
		"10", -- [6]
		"15", -- [7]
		[9] = 1574403235,
	}, -- [7]
	{
		"Akfaceshot", -- [1]
		"Gokusoul", -- [2]
		"Add EP +1 (11/21 kaihuang)", -- [3]
		1, -- [4]
		2, -- [5]
		10, -- [6]
		10, -- [7]
		[9] = 1574407403,
	}, -- [8]
}
CEPGP_raid_logs = {
}
CEPGP_standby_accept_whispers = false
CEPGP_standby_byrank = true
CEPGP_standby_manual = false
CEPGP_standby_whisper_msg = "standby"
CEPGP_notice = true
CEPGP_keyword = "!need"
ALLOW_FORCED_SYNC = false
CEPGP_force_sync_rank = 1
CEPGP_loot_GUI = true
CEPGP_auto_pass = false
CEPGP_raid_wide_dist = true
CEPGP_standby_share = false
CEPGP_1120_notice = true
CEPGP_min_threshold = 3
CEPPG_gp_tooltips = true
CEPGP_standbyRoster = {
}
CEPGP_suppress_announcements = false
CEPGP_minEP = {
	false, -- [1]
	10, -- [2]
}
CEPGP_minGPDecayFactor = nil
